POST http://localhost:3001/api/notes/ 
Content-Type: application/json

{
    "content": "posting a note"
}

### 
# con lo de arriba separas para varios ejemplos

POST http://localhost:5500/api/notes/ 
Content-Type: application/json

{
}

